version: '2'
services:
    django:
        image: django
        volumes: 
             - /data/RedisOPM/WebMM:/code
        ports:
             - 8080:8000
        networks:
             - NetRedis
        working_dir: /code
        command: python manage.py runserver 0.0.0.0:8000

networks:
    NetRedis:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24
                  ip_range: 10.0.0.0/24
                  gateway: 10.0.0.1
